### ISSUE TITLE
TODO: add Python 3 support

### ISSUE THREAD

**Issue by jlu5** [GLolol/SupyPlugins#12]
and maybe some unit tests too while we're at it because why not?

Plugins to check for Python 3 support:
- [X] Isup - f9f6ffc
- [X] NoTrigger - 3ff1f8e
- [ ] OperUp - believed to be working, untested
- [X] PassGen _(no modifications needed)_
- [X] PkgInfo - 98914e1 4dc9dd9
- [X] Randomness - 4d17daa
- [X] RelayLink - believed to be working as of 4dc9dd9, not fully tested
- [x] SupyMisc
- [X] SysDNS _(no modifications needed)_
- [X] TLDInfo - 4dc9dd9

Other tasks:
- [x] ~~Write a **py3support.md** detailing what plugins support Python 3.~~ This isn't needed.
- [ ] Test for python 2 compatibility - lol.
