### ISSUE TITLE
TODO: Allow PMs across networks for RelayLink

### ISSUE THREAD

**Issue by jlu5** [GLolol/SupyPlugins#5]
- [x] add a pm command
- [x] allow it to be turned on and off (globally) via config
- [x] check to see if the two users have common channels; if not, abort
- [x] handle one-way relays correctly per above
